version: "2"
services:
  jenkins-docker:
    image: docker:dind
    ports:
    - "2376:2376"
    environment:
    - DOCKER_TLS_CERTDIR=/certs
    volumes:
    - jenkins-data:/var/jenkins_home
    - jenkins-docker-certs:/certs/client
    networks:
      jenkins:
        aliases:
          - docker
    privileged: true

  jenkins-blueocean:
    image: jenkinsci/blueocean
    ports:
        - "8080:8080"
        - "50000:50000"
    environment:
    - DOCKER_HOST=tcp://docker:2376
    - DOCKER_CERT_PATH=/certs/client
    - DOCKER_TLS_VERIFY=1
    volumes:
    - jenkins-docker-certs:/certs/client:ro
    - jenkins-data:/var/jenkins_home
    networks:
    - jenkins

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins: